INSERT INTO [dbo].[OPERATION]([NAME],[DESCRIPTION],[CODE],[INTERNAL_COMPANY_ID],[TYPE_ID],[STATUS],[CREATE_USER],[CREATE_TIMESTAMP],[UPDATE_USER],[UPDATE_TIMESTAMP])
	SELECT 'Administrative fee order','Administrative fee order','AADMFEEORDER', c.COMPANYNR, ot.OPERATION_TYPE_ID, 0,'system', getdate(), 'system', getdate()
	FROM COMPANY c, OPERATION_TYPE ot where c.CODE = 'IC_VMHZP' and ot.[DESCRIPTION]='Additional'
insert into [dbo].[ADDITIONAL_OPERATION] ([ADDITIONAL_OPERATION_ID],[USAGE],[CREATE_USER],[CREATE_TIMESTAMP],[UPDATE_USER],[UPDATE_TIMESTAMP] )
	select o.OPERATION_ID , 1,'system', getdate(), 'system', getdate() from OPERATION o where o.CODE = 'AADMFEEORDER'
insert into OPERATION_ADDITIONAL_OPERATION
	select o.OPERATION_ID, ao.OPERATION_ID
	from OPERATION o, OPERATION ao
	where o.INTERNAL_COMPANY_ID = ao.INTERNAL_COMPANY_ID
	and o.OPERATION_ID in (select LOADING_OPERATION_ID from LOADING_OPERATION union select DISCHARGING_OPERATION_ID from DISCHARGING_OPERATION)
	and ao.CODE = 'AADMFEEORDER'
insert into [dbo].[ADDITIONAL_OPERATION_COMPANY]([ADDITIONAL_OPERATION_ID],[COMPANYNR]) select o.OPERATION_ID, c.COMPANYNR from OPERATION o, COMPANY c where o.CODE='AADMFEEORDER' and c.CODE ='RPC'
--exec #CreateTariff 'TACLRSPRAY', 'Colorspraying', 0, 'PCS', null,'EUR', 'ACLRSPRAY', 'A', 'RPC'

INSERT INTO [dbo].[OPERATION]([NAME],[DESCRIPTION],[CODE],[INTERNAL_COMPANY_ID],[TYPE_ID],[STATUS],[CREATE_USER],[CREATE_TIMESTAMP],[UPDATE_USER],[UPDATE_TIMESTAMP])
	SELECT 'Labelling','Labelling','ALABNG', c.COMPANYNR, ot.OPERATION_TYPE_ID, 0,'system', getdate(), 'system', getdate()
	FROM COMPANY c, OPERATION_TYPE ot where c.CODE = 'IC_VMHZP' and ot.[DESCRIPTION]='Additional'
insert into [dbo].[ADDITIONAL_OPERATION] ([ADDITIONAL_OPERATION_ID],[USAGE],[CREATE_USER],[CREATE_TIMESTAMP],[UPDATE_USER],[UPDATE_TIMESTAMP] )
	select o.OPERATION_ID , 1,'system', getdate(), 'system', getdate() from OPERATION o where o.CODE = 'ALABNG'
insert into OPERATION_ADDITIONAL_OPERATION
	select o.OPERATION_ID, ao.OPERATION_ID
	from OPERATION o, OPERATION ao
	where o.INTERNAL_COMPANY_ID = ao.INTERNAL_COMPANY_ID
	and o.OPERATION_ID in (select LOADING_OPERATION_ID from LOADING_OPERATION union select DISCHARGING_OPERATION_ID from DISCHARGING_OPERATION)
	and ao.CODE = 'ALABNG'
--exec #CreateTariff 'TACLRSPRAY', 'Colorspraying', 0, 'PCS', null,'EUR', 'ACLRSPRAY', 'A', 'RPC'

insert into [dbo].[ADDITIONAL_OPERATION_COMPANY]([ADDITIONAL_OPERATION_ID],[COMPANYNR]) select o.OPERATION_ID, c.COMPANYNR from OPERATION o, COMPANY c where o.CODE='ALABNG' and c.CODE ='RPC'

40561:RPC - Operational revenue

customer code 'RPC'

Insert two tariff files :
+ Minimum amount (reference = 'MINFIXEDTARIFF') - 30 EUR per transport
+ L/D - 1 EUR/PAL
