declare @OperationReportId int = 5243
select STOCK_CHANGE_OPERATION_REPORT_ID, 'SC' as [TYPE] from STOCK_CHANGE_OPERATION_REPORT where STOCK_CHANGE_OPERATION_REPORT_ID = @OperationReportId
union select LOADING_OPERATION_REPORT_ID, 'LD' from LOADING_OPERATION_REPORT where LOADING_OPERATION_REPORT_ID = @OperationReportId
union select DISCHARGING_OPERATION_REPORT_ID, 'DC' from DISCHARGING_OPERATION_REPORT where DISCHARGING_OPERATION_REPORT_ID = @OperationReportId
union select VAS_OPERATION_REPORT_ID, 'VAS' from VAS_OPERATION_REPORT where VAS_OPERATION_REPORT_ID = @OperationReportId
